services:
  db:
    image: mysql:8.0
    container_name: e_spirit_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: e_spirit_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: e_spirit_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    container_name: fastapi_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=e_spirit_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: